sudo: required
services:
  - docker

before_install:
  - docker build -t patw0929/udemy-docker-deploy-practice -f Dockerfile.dev .

script:
  - docker run patw0929/udemy-docker-deploy-practice npm test -- --coverage
